### ISSUE TITLE
PriceFound will throw exceptions if no price is found

### ISSUE THREAD

**Issue by jcoddaire** [reserad/Build-a-PC-Sales-Deal-Hunter#2]
This should have a try catch and return 0 if something bad happens. What if the passed Title has no numbers?

``` c#
public int PriceFound(string Title)
        {
            char ch = Title[0];
            int i = 0;
            while (ch != '$')
            {
                ch = Title[i];
                i++;
            }
            var digits = Title.Substring(i, Title.Length - i).SkipWhile(c => !Char.IsDigit(c))
                .TakeWhile(Char.IsDigit)
                .ToArray();

            var str = new string(digits);
            return int.Parse(str);
        }
```

**Comment by reserad** [comment]
This is what I had before I realized a mistake I had:
int price;
            foreach(var task in tm)
            {
                foreach (var product in ListOfStoredProducts)
                {
                    if (product.Title.ToLower().Contains(task.Query.ToLower()))
                    {
                        int price;
                        try
                        {
                            price = PriceFound(product.Title);
                        }
                        catch(Exception e)
                        {
                            return;
                        }
etc...

I realized the 'return' needs to be a 'break'.

This would circumnavigate the need to return 0 since I already have a try catch in place... right?
